// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *presentes → images*
 */
export interface PresentesDocumentDataImagesItem {
  /**
   * url field in *presentes → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: presentes.images[].url
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  url: prismic.ImageField<never>;
}

/**
 * Item in *presentes → links_reference*
 */
export interface PresentesDocumentDataLinksReferenceItem {
  /**
   * label field in *presentes → links_reference*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Label do link de referencia (Nome do site ou nome do link)
   * - **API ID Path**: presentes.links_reference[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * href field in *presentes → links_reference*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link de referencia
   * - **API ID Path**: presentes.links_reference[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField;
}

type PresentesDocumentDataSlicesSlice = never;

/**
 * Content for presentes documents
 */
interface PresentesDocumentData {
  /**
   * name field in *presentes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome do presente
   * - **API ID Path**: presentes.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * category field in *presentes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Categoria do presente (Cozinha, quarto, eletro domesticos...)
   * - **API ID Path**: presentes.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;

  /**
   * is_paid field in *presentes*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: presentes.is_paid
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_paid: prismic.BooleanField;

  /**
   * images field in *presentes*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: presentes.images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<PresentesDocumentDataImagesItem>>;

  /**
   * is_archoved field in *presentes*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: presentes.is_archoved
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_archoved: prismic.BooleanField;

  /**
   * links_reference field in *presentes*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: presentes.links_reference[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links_reference: prismic.GroupField<
    Simplify<PresentesDocumentDataLinksReferenceItem>
  >;

  /**
   * is_for_delivery field in *presentes*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: presentes.is_for_delivery
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_for_delivery: prismic.BooleanField;

  /**
   * price field in *presentes*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Preço do presente
   * - **API ID Path**: presentes.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;

  /**
   * link_paid field in *presentes*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link de pagamento (Nubank -Pix- ou Stripe -Cartões-)
   * - **API ID Path**: presentes.link_paid
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_paid: prismic.LinkField;

  /**
   * Slice Zone field in *presentes*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: presentes.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PresentesDocumentDataSlicesSlice> /**
   * Meta Title field in *presentes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: presentes.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *presentes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: presentes.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *presentes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: presentes.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * presentes document from Prismic
 *
 * - **API ID**: `presentes`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PresentesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PresentesDocumentData>,
    "presentes",
    Lang
  >;

type ResumoDocumentDataSlicesSlice = never;

/**
 * Content for resumo documents
 */
interface ResumoDocumentData {
  /**
   * cerimonia_date field in *resumo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Data da cerimonia
   * - **API ID Path**: resumo.cerimonia_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cerimonia_date: prismic.KeyTextField;

  /**
   * cerimonia_time field in *resumo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hora da cerimonia
   * - **API ID Path**: resumo.cerimonia_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cerimonia_time: prismic.KeyTextField;

  /**
   * cerimonia_location field in *resumo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Local da cerimonia
   * - **API ID Path**: resumo.cerimonia_location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cerimonia_location: prismic.KeyTextField;

  /**
   * recepcao_date field in *resumo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Data da recepcao
   * - **API ID Path**: resumo.recepcao_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  recepcao_date: prismic.KeyTextField;

  /**
   * recepcao_time field in *resumo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hora da recepcao
   * - **API ID Path**: resumo.recepcao_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  recepcao_time: prismic.KeyTextField;

  /**
   * recepcao_location field in *resumo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Local da recepcao
   * - **API ID Path**: resumo.recepcao_location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  recepcao_location: prismic.KeyTextField;

  /**
   * Slice Zone field in *resumo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: resumo.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ResumoDocumentDataSlicesSlice>;
}

/**
 * resumo document from Prismic
 *
 * - **API ID**: `resumo`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ResumoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ResumoDocumentData>, "resumo", Lang>;

export type AllDocumentTypes = PresentesDocument | ResumoDocument;

/**
 * Default variation for Presentes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PresentesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Presentes*
 */
type PresentesSliceVariation = PresentesSliceDefault;

/**
 * Presentes Shared Slice
 *
 * - **API ID**: `presentes`
 * - **Description**: Presentes
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PresentesSlice = prismic.SharedSlice<
  "presentes",
  PresentesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PresentesDocument,
      PresentesDocumentData,
      PresentesDocumentDataImagesItem,
      PresentesDocumentDataLinksReferenceItem,
      PresentesDocumentDataSlicesSlice,
      ResumoDocument,
      ResumoDocumentData,
      ResumoDocumentDataSlicesSlice,
      AllDocumentTypes,
      PresentesSlice,
      PresentesSliceVariation,
      PresentesSliceDefault,
    };
  }
}
